ALTER TABLE "User"
ADD COLUMN "showProfileSection" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "showPreferencesSection" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "showFeedSection" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "showGoalsSection" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "showFriendsSection" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "WordGoal"
ALTER COLUMN "dailyTargetWords" SET DEFAULT 500,
ADD COLUMN "streakGoalDays" INTEGER NOT NULL DEFAULT 7;
